{
  "$schema": "http://json.schemastore.org/package",
  "author": "wcarmon",
  "dependencies": {
    "@angular-material-components/color-picker": "~5.0.2",
    "@angular/animations": "~11.0.9",
    "@angular/cdk": "~11.0.4",
    "@angular/common": "~11.0.9",
    "@angular/compiler": "~11.0.9",
    "@angular/core": "~11.0.9",
    "@angular/forms": "~11.0.9",
    "@angular/material": "~11.0.4",
    "@angular/platform-browser": "~11.0.9",
    "@angular/platform-browser-dynamic": "~11.0.9",
    "@angular/router": "~11.0.9",
    "auto-bind": "~4.0.0",
    "axios": "~0.21.1",
    "idb": "~5.0.8",
    "lodash-es": "~4.17.20",
    "normalize.css": "~8.0.1",
    "rxjs": "~6.6.0",
    "rxjs-es": "~5.0.0-beta.12",
    "tslib": "~2.0.3",
    "ub-common": "1.0.0",
    "ub-net": "1.0.0",
    "ub-persistence": "1.0.0",
    "uuid": "~8.3.2",
    "winston": "~3.3.3",
    "zone.js": "~0.10.2"
  },
  "description": "codegen-node-sandbox",
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.1100.7",
    "@angular/cli": "~11.0.7",
    "@angular/compiler-cli": "~11.0.9",
    "@types/chai": "~4.2.14",
    "@types/jasmine": "~3.6.3",
    "@types/lodash": "~4.14.168",
    "@types/lodash-es": "~4.17.4",
    "@types/mocha": "~8.2.0",
    "@types/node": "~12.11.7",
    "@types/uuid": "~8.3.0",
    "@typescript-eslint/eslint-plugin": "~4.14.0",
    "@typescript-eslint/parser": "~4.14.0",
    "barrelsby": "~2.2.0",
    "chai": "~4.2.0",
    "codelyzer": "~6.0.0",
    "eslint": "~7.16.0",
    "eslint-plugin-import": "~2.22.1",
    "eslint-plugin-sonarjs": "~0.5.0",
    "gulp": "~4.0.2",
    "jasmine": "~3.6.4",
    "jasmine-core": "~3.6.0",
    "jasmine-spec-reporter": "~5.0.0",
    "karma": "~5.1.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage": "~2.0.3",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "~1.5.0",
    "mocha": "~8.2.1",
    "prettier": "~2.2.1",
    "protractor": "~7.0.0",
    "ts-node": "~9.1.1",
    "tslint": "~6.1.0",
    "typescript": "~4.0.5"
  },
  "directories": {
    "test": "test"
  },
  "license": "ISC",
  "main": "dist/index.js",
  "name": "codegen-node-sandbox"
  "private": true,
  "scripts": {
    "build": "ng build",
    "e2e": "ng e2e",
    "lint": "ng lint",
    "ng": "ng",
    "pretty": "prettier --write ./src/**/*.{ts,tsx,js,jsx,json}",
    "start": "ng serve",
    "test": "ng test"
  },
  "types": "dist/index.d.ts",
  "version": "1.0.0"
}
