[#ftl]
[#-- @implicitly included --]
[#-- @ftlvariable name="entities" type="java.util.Collection<com.wcarmon.codegen.model.Entity>" --]
[#-- @ftlvariable name="entity" type="com.wcarmon.codegen.model.Entity" --]
[#-- @ftlvariable name="field" type="com.wcarmon.codegen.model.Field" --]
[#-- @ftlvariable name="request" type="com.wcarmon.codegen.model.CodeGenRequest" --]
